name: Windows (amd64)

on:
  push:
  workflow_dispatch:
    
jobs:

  ci:
    runs-on: windows-latest
    steps:
      - name: Test
        shell: cmd
        run: |
          set SIREUM_V=4.20241017.f6e1eff
          md "%USERPROFILE%\Applications"
          md "%USERPROFILE%\Downloads"
          curl -JLso %USERPROFILE%\Downloads\sireum-ive-win-amd64.zip https://github.com/sireum/kekinian/releases/download/%SIREUM_V%/sireum-ive-win-amd64.zip
          curl -JLso %USERPROFILE%\Downloads\org.sireum.library.m2.zip https://github.com/sireum/kekinian/releases/download/%SIREUM_V%/org.sireum.library.m2.zip  
          cd /d %USERPROFILE%\Applications
          tar xf %USERPROFILE%\Downloads\sireum-ive-win-amd64.zip
          cd /d "%USERPROFILE%"
          tar xf %USERPROFILE%\Downloads\org.sireum.library.m2.zip

          set SIREUM_HOME=%USERPROFILE%\Applications\Sireum
          
          git clone https://github.com/sireum/logika-examples

          echo before verify
          logika-examples\bin\verify.cmd
          echo "past verify.cmd"
          %SIREUM_HOME%\bin\sireum.bat proyek ive logika-examples
