name: Linux 20.04 (amd64)

on:
  push:
  workflow_dispatch:
    
jobs:

  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Test
        run: |
          export SIREUM_V=4.20241017.f6e1eff
          mkdir -p ~/Applications ~/Downloads
          curl -JLso ~/Downloads/sireum-ive-linux-amd64.tar.xz https://github.com/sireum/kekinian/releases/download/$SIREUM_V/sireum-ive-linux-amd64.tar.xz
          curl -JLso ~/Downloads/org.sireum.library.m2.zip https://github.com/sireum/kekinian/releases/download/$SIREUM_V/org.sireum.library.m2.zip  
          cd ~/Applications
          tar xf ~/Downloads/sireum-ive-linux-amd64.tar.xz
          cd ~
          unzip ~/Downloads/org.sireum.library.m2.zip

          export SIREUM_HOME=~/Applications/Sireum
          
          # Z3 4.12+ requires glibc 2.35+ but ubuntu-20.04 provides glibc 2.31 so replace
          # the Z3 Sireum provides with Z3 2.31
          curl -JLso ~/Downloads/z3-4.11.2-x64-glibc-2.31.zip https://github.com/Z3Prover/z3/releases/download/z3-4.11.2/z3-4.11.2-x64-glibc-2.31.zip
          unzip ~/Downloads/z3-4.11.2-x64-glibc-2.31.zip
          rm -rf $SIREUM_HOME/bin/linux/z3
          mv ~/z3-4.11.2-x64-glibc-2.31 $SIREUM_HOME/bin/linux/z3

          $SIREUM_HOME/bin/linux/z3/bin/z3 --version

          git clone https://github.com/jasonbelt/logika-examples.git
          logika-examples/bin/verify.cmd
          "${SIREUM_HOME}/bin/sireum" proyek ive logika-examples
